In [1]:
from pyscf import gto, lib
import numpy as np
import itertools

np.set_printoptions(16)

In [2]:
lib.num_threads(32)

32

In [3]:
mol = gto.Mole(atom="O; H 1 0.94; H 1 0.94 2 104.5", basis="def2-TZVP").build()

In [4]:
nshl = mol.nbas, 1
nao = mol.nao
nao, nshl

(43, (19, 1))

## test_int3c2e_s1_full

In [5]:
out = mol.intor("int3c2e")
out_c = out.transpose(2, 1, 0)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

5372.255349662842
549.9144320716556


## int3c2e_s1_slice

In [6]:
out = mol.intor("int3c2e", shls_slice=(3, 15, 6, 12, 2, 18))
out_c = out.transpose(2, 1, 0)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

2061.267953944021
301.27148204542175


## int3c2e_ip1_s1_slice

In [7]:
out = mol.intor("int3c2e_ip1", shls_slice=(3, 15, 6, 12, 2, 18))
out_c = out.transpose(0, 3, 2, 1)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

-708.4938257710874
-206.84642420675885


## int2c2e_ip1_s1_slice

In [8]:
out = mol.intor("int2c2e_ip1", shls_slice=(3, 15, 6, 12))
out_c = out.transpose(0, 2, 1)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

-133.92961573356592
13.149333776387465


## int2c2e_ip1ip2_s1_slice

In [9]:
out = mol.intor("int2e_ip1ip2", shls_slice=(3, 15, 6, 12, 2, 18, 7, 11))
out_c = out.transpose(0, 4, 3, 2, 1).copy()
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

754.4717054716847
153.0307989722583


## int3c2e_s2ij_full

In [10]:
out = mol.intor("int3c2e", aosym="s2ij")
out_c = out.transpose(1, 0)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

3505.0701294680757
354.77408197530985


## int3c2e_ip2_s2ij_slice

In [11]:
out = mol.intor("int3c2e_ip2", shls_slice=(0, 15, 0, 15, 6, 12), aosym="s2ij")
out_c = out.transpose(0, 2, 1)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

484.24278790302156
-85.4382604552415


**Note** In pyscf, it seems that `s2ij` in `getints3c`, starting shell should always zero, otherwise it may not seems to be correct.

## int2e_ip2_s2ij_slice

In [12]:
out = mol.intor("int2e_ip2", shls_slice=(3, 15, 3, 15, 6, 12, 7, 11), aosym="s2ij")
out_c = out.transpose(0, 3, 2, 1).copy()
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

-290.5233235501449
-178.07946594201977


## int2c2e_s2ij_slice

In [13]:
out = mol.intor("int2c2e", shls_slice=(3, 15, 3, 15), aosym="s2ij")
out_c = out[np.tril_indices(out.shape[0])]
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out_c.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

929.2845254621801
77.98393796393151


## Molecule information

In [14]:
np.set_printoptions(threshold=1e15)

In [15]:
mol._atm

array([[ 8, 20,  1, 23,  0,  0],
       [ 1, 24,  1, 27,  0,  0],
       [ 1, 28,  1, 31,  0,  0]], dtype=int32)

In [16]:
mol._bas

array([[ 0,  0,  6,  1,  0, 44, 50,  0],
       [ 0,  0,  2,  1,  0, 56, 58,  0],
       [ 0,  0,  1,  1,  0, 60, 61,  0],
       [ 0,  0,  1,  1,  0, 62, 63,  0],
       [ 0,  0,  1,  1,  0, 64, 65,  0],
       [ 0,  1,  4,  1,  0, 66, 70,  0],
       [ 0,  1,  1,  1,  0, 74, 75,  0],
       [ 0,  1,  1,  1,  0, 76, 77,  0],
       [ 0,  2,  1,  1,  0, 78, 79,  0],
       [ 0,  2,  1,  1,  0, 80, 81,  0],
       [ 0,  3,  1,  1,  0, 82, 83,  0],
       [ 1,  0,  3,  1,  0, 32, 35,  0],
       [ 1,  0,  1,  1,  0, 38, 39,  0],
       [ 1,  0,  1,  1,  0, 40, 41,  0],
       [ 1,  1,  1,  1,  0, 42, 43,  0],
       [ 2,  0,  3,  1,  0, 32, 35,  0],
       [ 2,  0,  1,  1,  0, 38, 39,  0],
       [ 2,  0,  1,  1,  0, 40, 41,  0],
       [ 2,  1,  1,  1,  0, 42, 43,  0]], dtype=int32)

In [17]:
mol._env

array([ 0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        1.7763425570911580e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
       -4.4476065664656128e-01,  0.0000000000000000e+00,
        1.7197618551510188e+00,  0.0000000000000000e+00,
        3.4061340999999999e+01,  5.1235746000000004e+00,
        1.1646626000000000e+00,

In [18]:
! lscpu

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  32
  On-line CPU(s) list:   0-31
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 9 7945HX with Radeon Graphics
    CPU family:          25
    Model:               97
    Thread(s) per core:  2
    Core(s) per socket:  16
    Socket(s):           1
    Stepping:            2
    Frequency boost:     enabled
    CPU max MHz:         5461.0000
    CPU min MHz:         400.0000
    BogoMIPS:            4990.87
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mc
                         a cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall n
                         x mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_go
                         od amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfm
                         perf rapl pni pclmul