In [1]:
from pyscf import gto, lib
import numpy as np
import itertools

np.set_printoptions(16)
lib.num_threads(16)

16

In [2]:
%%time
mol = gto.Mole(atom="""
SB        -1.33937843      0.44597852     -1.27279684
SB         1.33937843     -0.44597852     -1.27279684
C         -1.40429524      1.10441871      0.83468205
C         -2.16210130     -1.56132398     -0.84717555
C          2.16210130      1.56132398     -0.84717555
C          1.40429524     -1.10441871      0.83468205
H         -0.69918639      1.91987631      1.00872018
H         -1.16111477      0.29030616      1.51873028
H         -2.40124532      1.47235562      1.08516843
H         -2.02002046     -2.22909286     -1.69887295
H         -1.69052287     -2.01612927      0.02577778
H         -3.23450854     -1.49489801     -0.65423339
H          2.02002046      2.22909286     -1.69887295
H          3.23450854      1.49489801     -0.65423339
H          1.69052287      2.01612927      0.02577778
H          0.69918639     -1.91987631      1.00872018
H          2.40124532     -1.47235562      1.08516843
H          1.16111477     -0.29030616      1.51873028
""", basis="def2-TZVP", ecp={"SB": "def2-TZVP"}).build()

CPU times: user 16.9 ms, sys: 60.9 ms, total: 77.7 ms
Wall time: 4.85 ms


## test_ECPscalar

In [3]:
out = mol.intor("ECPscalar")
out_c = out.transpose(1, 0)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

2844.388262741379
-2316.524453049404


## test_ECPscalar_ipnuc

In [4]:
out = mol.intor("ECPscalar_ipnuc", shls_slice=(7, 93, 14, 121))
out_c = out.transpose(0, 2, 1)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

-2332.269421722938
702.9250770858847


## test_ECPscalar_ipiprinv

In [5]:
out = mol.intor("ECPscalar_ipiprinv", shls_slice=(7, 93, 14, 121), comp=9)
out_c = out.transpose(0, 2, 1)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

101.618985700688
16.880187076578714


## test_ECPscalar_ignuc

In [6]:
out = mol.intor("ECPscalar_ignuc", shls_slice=(7, 93, 14, 121))
out_c = out.transpose(0, 2, 1)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

45.903159687209964
0.21557173801319873


## test_ECPscalar_ignuc_cart

In [7]:
out = mol.intor("ECPscalar_ignuc_cart", shls_slice=(7, 93, 14, 121))
out_c = out.transpose(0, 2, 1)
assert out_c.flags.c_contiguous
scale = np.linspace(-1, 1, out.size)
print(out_c.sum())
print((out_c.flatten() * scale).sum())

111.56926252707224
-77.65227858432043


## Molecule information

In [8]:
mol._atm

array([[23, 20,  4, 23,  0,  0],
       [23, 24,  4, 27,  0,  0],
       [ 6, 28,  1, 31,  0,  0],
       [ 6, 32,  1, 35,  0,  0],
       [ 6, 36,  1, 39,  0,  0],
       [ 6, 40,  1, 43,  0,  0],
       [ 1, 44,  1, 47,  0,  0],
       [ 1, 48,  1, 51,  0,  0],
       [ 1, 52,  1, 55,  0,  0],
       [ 1, 56,  1, 59,  0,  0],
       [ 1, 60,  1, 63,  0,  0],
       [ 1, 64,  1, 67,  0,  0],
       [ 1, 68,  1, 71,  0,  0],
       [ 1, 72,  1, 75,  0,  0],
       [ 1, 76,  1, 79,  0,  0],
       [ 1, 80,  1, 83,  0,  0],
       [ 1, 84,  1, 87,  0,  0],
       [ 1, 88,  1, 91,  0,  0]], dtype=int32)

In [9]:
mol._bas

array([[  0,   0,   4,   1,   0, 144, 148,   0],
       [  0,   0,   2,   1,   0, 152, 154,   0],
       [  0,   0,   1,   1,   0, 156, 157,   0],
       [  0,   0,   1,   1,   0, 158, 159,   0],
       [  0,   0,   1,   1,   0, 160, 161,   0],
       [  0,   0,   1,   1,   0, 162, 163,   0],
       [  0,   1,   3,   1,   0, 164, 167,   0],
       [  0,   1,   3,   1,   0, 170, 173,   0],
       [  0,   1,   1,   1,   0, 176, 177,   0],
       [  0,   1,   1,   1,   0, 178, 179,   0],
       [  0,   1,   1,   1,   0, 180, 181,   0],
       [  0,   2,   6,   1,   0, 182, 188,   0],
       [  0,   2,   1,   1,   0, 194, 195,   0],
       [  0,   2,   1,   1,   0, 196, 197,   0],
       [  0,   3,   1,   1,   0, 198, 199,   0],
       [  0,   3,   1,   1,   0, 200, 201,   0],
       [  1,   0,   4,   1,   0, 144, 148,   0],
       [  1,   0,   2,   1,   0, 152, 154,   0],
       [  1,   0,   1,   1,   0, 156, 157,   0],
       [  1,   0,   1,   1,   0, 158, 159,   0],
       [  1,   0,   

In [10]:
mol._env

array([ 0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        0.0000000000000000e+00,  0.0000000000000000e+00,
        1.2400000000000000e+02,  8.0000000000000000e+00,
       -2.5310584098499369e+00,  8.4277726023886190e-01,
       -2.4052374398118572e+00,  0.0000000000000000e+00,
        2.5310584098499369e+00, -8.4277726023886190e-01,
       -2.4052374398118572e+00,  0.0000000000000000e+00,
       -2.6537334016303631e+00,  2.0870488887454450e+00,
        1.5773204755905210e+00,  0.0000000000000000e+00,
       -4.0857793105660818e+00, -2.9504747139158982e+00,
       -1.6009297689277748e+00,

In [11]:
mol._ecpbas

array([[  0,  -1,   2,   2,   0, 202, 204,   0],
       [  0,   0,   4,   2,   0, 206, 210,   0],
       [  0,   1,   6,   2,   0, 214, 220,   0],
       [  0,   2,   6,   2,   0, 226, 232,   0],
       [  1,  -1,   2,   2,   0, 202, 204,   0],
       [  1,   0,   4,   2,   0, 206, 210,   0],
       [  1,   1,   6,   2,   0, 214, 220,   0],
       [  1,   2,   6,   2,   0, 226, 232,   0]], dtype=int32)